from AgentCrew.modules.llm.types import Model, SampleParam

COMMANDCODE_MODELS = [
    Model(
        id="claude-fable-5",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Fable 5",
        description="Anthropic Claude Fable 5 via CommandCode — most capable for demanding reasoning and long-horizon agents",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=10.000000,
        output_token_price_1m=50.000000,
        cached_token_price_1m=1.000000,
    ),
    Model(
        id="claude-sonnet-4-6",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Sonnet 4.6",
        description="Anthropic Claude Sonnet 4.6 via CommandCode — advanced agentic coding and reasoning with vision and extended thinking",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        default=False,
        input_token_price_1m=3.000000,
        output_token_price_1m=15.000000,
        cached_token_price_1m=0.300000,
    ),
    Model(
        id="claude-sonnet-5",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Sonnet 5",
        description="Anthropic Claude Sonnet 5 via CommandCode — most agentic Sonnet yet with near-Opus performance for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=2.000000,
        output_token_price_1m=10.000000,
        cached_token_price_1m=0.200000,
    ),
    Model(
        id="claude-opus-4-8",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Opus 4.8",
        description="Anthropic Claude Opus 4.8 via CommandCode — maximum intelligence for specialized reasoning and complex agentic workflows",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=5.000000,
        output_token_price_1m=25.000000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="claude-opus-4-7",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Opus 4.7",
        description="Anthropic Claude Opus 4.7 via CommandCode — maximum intelligence for specialized reasoning and complex agentic workflows",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=5.000000,
        output_token_price_1m=25.000000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="claude-haiku-4-5-20251001",
        provider="commandcode",
        service_name="commandcode_anthropic",
        name="Claude Haiku 4.5",
        description="Anthropic Claude Haiku 4.5 via CommandCode — fast and efficient near-frontier intelligence",
        capabilities=["tool_use", "vision", "stream"],
        max_context_token=200_000,
        input_token_price_1m=1.000000,
        output_token_price_1m=5.000000,
        cached_token_price_1m=0.100000,
    ),
    Model(
        id="gpt-5.6-sol",
        provider="commandcode",
        name="GPT-5.6 Sol",
        description="OpenAI GPT-5.6 Sol via CommandCode — frontier model for complex professional work",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=250_000,
        input_token_price_1m=5.000000,
        output_token_price_1m=30.000000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="gpt-5.6-terra",
        provider="commandcode",
        name="GPT-5.6 Terra",
        description="OpenAI GPT-5.6 Terra via CommandCode — balanced frontier intelligence and cost",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_050_000,
        input_token_price_1m=2.500000,
        output_token_price_1m=15.000000,
        cached_token_price_1m=0.250000,
    ),
    Model(
        id="gpt-5.6-luna",
        provider="commandcode",
        name="GPT-5.6 Luna",
        description="OpenAI GPT-5.6 Luna via CommandCode — cost-efficient model for general workloads",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_050_000,
        input_token_price_1m=1.000000,
        output_token_price_1m=6.000000,
        cached_token_price_1m=0.100000,
    ),
    Model(
        id="gpt-5.5",
        provider="commandcode",
        name="GPT-5.5",
        description="OpenAI GPT-5.5 via CommandCode — flagship model with vision, reasoning, and structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=5.000000,
        output_token_price_1m=30.000000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="gpt-5.4",
        provider="commandcode",
        name="GPT-5.4",
        description="OpenAI GPT-5.4 via CommandCode — balanced performance with vision, reasoning, and structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=2.500000,
        output_token_price_1m=15.000000,
        cached_token_price_1m=0.250000,
    ),
    Model(
        id="gpt-5.3-codex",
        provider="commandcode",
        name="GPT-5.3 Codex",
        description="OpenAI GPT-5.3 Codex via CommandCode — code-optimized model with reasoning and structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=2.000000,
        output_token_price_1m=8.000000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="gpt-5.4-mini",
        provider="commandcode",
        name="GPT-5.4 Mini",
        description="OpenAI GPT-5.4 Mini via CommandCode — fast and cost-effective model for simpler tasks",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.750000,
        output_token_price_1m=4.500000,
        cached_token_price_1m=0.075000,
    ),
    Model(
        id="moonshotai/Kimi-K3",
        provider="commandcode",
        name="Kimi K3",
        description="MoonshotAI Kimi K3 via CommandCode — flagship model for long-horizon coding & knowledge work with 1M context, vision and always-on reasoning",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        max_context_token=500_000,
        input_token_price_1m=3.000000,
        output_token_price_1m=15.000000,
        cached_token_price_1m=0.300000,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="commandcode",
        name="Kimi K2.6",
        description="MoonshotAI Kimi K2.6 via CommandCode — vision-capable reasoning model with structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.950000,
        output_token_price_1m=4.000000,
        cached_token_price_1m=0.160000,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="commandcode",
        name="Kimi K2.5",
        description="MoonshotAI Kimi K2.5 via CommandCode — vision-capable reasoning model with structured output",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.600000,
        output_token_price_1m=3.000000,
        cached_token_price_1m=0.100000,
    ),
    Model(
        id="moonshotai/Kimi-K2.7-Code",
        provider="commandcode",
        name="Kimi K2.7 Code",
        description="MoonshotAI Kimi K2.7 Code via CommandCode — coding-focused agentic model with vision, improved long-horizon coding and 30% fewer thinking tokens",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        max_context_token=256_000,
        input_token_price_1m=0.950000,
        output_token_price_1m=4.000000,
        cached_token_price_1m=0.190000,
    ),
    Model(
        id="moonshotai/Kimi-K2.7-Code-Highspeed",
        provider="commandcode",
        name="Kimi K2.7 Code HighSpeed",
        description="MoonshotAI Kimi K2.7 Code HighSpeed via CommandCode — faster long-horizon coding with vision",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        max_context_token=262_000,
        input_token_price_1m=1.900000,
        output_token_price_1m=8.000000,
        cached_token_price_1m=0.380000,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="commandcode",
        name="GLM-5.1",
        description="Z.ai GLM-5.1 via CommandCode — long-context reasoning model optimized for agentic workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=1.400000,
        output_token_price_1m=4.400000,
        cached_token_price_1m=0.260000,
    ),
    Model(
        id="zai-org/GLM-5.2",
        provider="commandcode",
        name="GLM-5.2",
        description="Z.ai GLM-5.2 via CommandCode — long-context reasoning model optimized for agentic workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=1.400000,
        output_token_price_1m=4.400000,
        cached_token_price_1m=0.260000,
    ),
    Model(
        id="zai-org/GLM-5.2-Fast",
        provider="commandcode",
        name="GLM-5.2 Fast",
        description="Z.ai GLM-5.2 Fast via CommandCode — high-throughput GLM-5.2 serving with a 1M context window",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=128_000,
        input_token_price_1m=3.000000,
        output_token_price_1m=10.250000,
        cached_token_price_1m=0.500000,
    ),
    Model(
        id="zai-org/GLM-5",
        provider="commandcode",
        name="GLM-5",
        description="Z.ai GLM-5 via CommandCode — efficient model for agentic and coding workloads",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        max_context_token=200_000,
        input_token_price_1m=1.000000,
        output_token_price_1m=3.200000,
        cached_token_price_1m=0.200000,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M3",
        provider="commandcode",
        name="MiniMax M3",
        description="MiniMax M3 via CommandCode — coding and agentic model with reasoning support",
        capabilities=["thinking", "vision", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.225000,
        output_token_price_1m=0.900000,
        cached_token_price_1m=0.045000,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.7",
        provider="commandcode",
        name="MiniMax M2.7",
        description="MiniMax M2.7 via CommandCode — coding and agentic model with reasoning support",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.300000,
        output_token_price_1m=1.200000,
        cached_token_price_1m=0.060000,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.5",
        provider="commandcode",
        name="MiniMax M2.5",
        description="MiniMax M2.5 via CommandCode — efficient coding and agentic model",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        max_context_token=200_000,
        input_token_price_1m=0.300000,
        output_token_price_1m=1.200000,
        cached_token_price_1m=0.030000,
    ),
    Model(
        id="deepseek/deepseek-v4-pro",
        provider="commandcode",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro via CommandCode — advanced reasoning model for complex agentic workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.435000,
        output_token_price_1m=0.870000,
        cached_token_price_1m=0.003625,
    ),
    Model(
        id="deepseek/deepseek-v4-flash",
        provider="commandcode",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash via CommandCode — fast lower-latency model for agentic and coding workloads",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        max_context_token=400_000,
        input_token_price_1m=0.140000,
        output_token_price_1m=0.280000,
        cached_token_price_1m=0.002800,
    ),
    Model(
        id="Qwen/Qwen3.6-Max-Preview",
        provider="commandcode",
        name="Qwen3.6 Max Preview",
        description="Qwen3.6 Max Preview via CommandCode — reasoning and agentic model for complex workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=1.300000,
        output_token_price_1m=7.800000,
        cached_token_price_1m=0.260000,
    ),
    Model(
        id="Qwen/Qwen3.6-Plus",
        provider="commandcode",
        name="Qwen3.6 Plus",
        description="Qwen3.6 Plus via CommandCode — efficient reasoning model for agentic and coding tasks",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=200_000,
        input_token_price_1m=0.500000,
        output_token_price_1m=3.000000,
        cached_token_price_1m=0.100000,
    ),
    Model(
        id="Qwen/Qwen3.7-Max",
        provider="commandcode",
        name="Qwen3.7 Max",
        description="Qwen3.7 Max via CommandCode — agent-first flagship model for coding, reasoning, and long-horizon AI workflows",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=1.250000,
        output_token_price_1m=3.750000,
        cached_token_price_1m=0.250000,
    ),
    Model(
        id="Qwen/Qwen3.7-Plus",
        provider="commandcode",
        name="Qwen3.7 Plus",
        description="Qwen3.7 Plus via CommandCode — high-performance reasoning model for agentic and coding workflows",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.400000,
        output_token_price_1m=1.600000,
        cached_token_price_1m=0.080000,
    ),
    Model(
        id="stepfun/Step-3.7-Flash",
        provider="commandcode",
        name="Step 3.7 Flash",
        description="StepFun Step 3.7 Flash via CommandCode — reasoning-capable MoE model optimized for agentic and coding workloads",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=256_000,
        input_token_price_1m=0.200000,
        output_token_price_1m=1.150000,
        cached_token_price_1m=0.040000,
    ),
    Model(
        id="stepfun/Step-3.5-Flash",
        provider="commandcode",
        name="Step 3.5 Flash",
        description="StepFun Step 3.5 Flash via CommandCode — sparse MoE model with frontier reasoning and agentic capabilities at 11B active parameters",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.100000,
        output_token_price_1m=0.300000,
        cached_token_price_1m=0.020000,
    ),
    Model(
        id="xiaomi/mimo-v2.5-pro",
        provider="commandcode",
        name="MiMo V2.5 Pro",
        description="Xiaomi MiMo V2.5 Pro via CommandCode — reasoning-capable model optimized for agentic and coding workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.435000,
        output_token_price_1m=0.870000,
        cached_token_price_1m=0.003600,
    ),
    Model(
        id="xiaomi/mimo-v2.5",
        provider="commandcode",
        name="MiMo V2.5",
        description="Xiaomi MiMo V2.5 via CommandCode — efficient model for general-purpose agentic and coding tasks",
        capabilities=["tool_use", "stream", "vision", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.140000,
        output_token_price_1m=0.280000,
        cached_token_price_1m=0.002800,
    ),
    Model(
        id="google/gemini-3.5-flash",
        provider="commandcode",
        name="Gemini 3.5 Flash",
        description="Google Gemini 3.5 Flash via CommandCode — vision-capable reasoning model balanced for speed and intelligence",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=1.500000,
        output_token_price_1m=9.000000,
        cached_token_price_1m=0.150000,
    ),
    Model(
        id="google/gemini-3.1-flash-lite",
        provider="commandcode",
        name="Gemini 3.1 Flash Lite",
        description="Google Gemini 3.1 Flash Lite via CommandCode — lightweight model for cost-effective high-throughput tasks",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.250000,
        output_token_price_1m=1.500000,
        cached_token_price_1m=0.030000,
    ),
    Model(
        id="tencent/Hy3",
        provider="commandcode",
        name="Tencent Hy3",
        description="Tencent Hy3 via CommandCode — sparse-MoE reasoning and agentic tool-use model",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
        cached_token_price_1m=0.0,
    ),
    Model(
        id="nvidia/nemotron-3-ultra-550b-a55b",
        provider="commandcode",
        name="Nemotron 3 Ultra",
        description="NVIDIA Nemotron 3 Ultra via CommandCode — open reasoning model for long-horizon autonomous agents",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        vision_model="xiaomi/mimo-v2.5",
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.600000,
        output_token_price_1m=2.400000,
        cached_token_price_1m=0.120000,
    ),
    Model(
        id="sakana/fugu-ultra",
        provider="commandcode",
        name="Fugu Ultra",
        description="Sakana Fugu Ultra via CommandCode — multi-agent orchestration system matching frontier performance on coding, reasoning, and agentic tasks",
        capabilities=["thinking", "vision", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=5.0,
        output_token_price_1m=30.0,
        cached_token_price_1m=0.5,
    ),
    Model(
        id="meta/muse-spark-1.1",
        provider="commandcode",
        name="Muse Spark 1.1",
        description="Meta Muse Spark 1.1 via CommandCode — agentic model with tool and computer-use capabilities",
        capabilities=["thinking", "tool_use", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=242_000,
        input_token_price_1m=1.250000,
        output_token_price_1m=4.250000,
        cached_token_price_1m=0.150000,
    ),
    Model(
        id="xai/grok-4.5",
        provider="commandcode",
        name="Grok 4.5",
        description="xAI Grok 4.5 via CommandCode — premium reasoning model for agentic workloads",
        capabilities=["thinking", "tool_use", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=500_000,
        input_token_price_1m=2.000000,
        output_token_price_1m=6.000000,
        cached_token_price_1m=0.500000,
    ),
]
