from AgentCrew.modules.llm.types import Model, SampleParam

GITHUB_COPILOT_MODELS = [
    # ── Anthropic ──────────────────────────────────────────────────────
    Model(
        id="claude-haiku-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude 4.5 Haiku",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-sonnet-5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Sonnet 5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.5 (Preview)",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.6",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.6",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.7",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.7",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=200_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.8",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.8",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-opus-4.8-fast",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Opus 4.8 (fast mode) (preview)",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="claude-fable-5",
        provider="github_copilot",
        service_name="github_copilot",
        name="Claude Fable 5",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=1_000_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    # ── Google Gemini ──────────────────────────────────────────────────
    Model(
        id="gemini-2.5-pro",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 2.5 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3-flash",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3 Flash",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3.1-pro",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3.1 Pro",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3.5-flash",
        provider="github_copilot",
        service_name="github_copilot",
        name="Gemini 3.5 Flash",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        force_sample_params=SampleParam(temperature=1.0),
        output_token_price_1m=0.0,
    ),
    # ── Microsoft ──────────────────────────────────────────────────────
    Model(
        id="mai-code-1-flash",
        provider="github_copilot",
        service_name="github_copilot",
        name="MAI-Code-1-Flash",
        description="Continuously improving model from Microsoft — performance and behavior may evolve over time.",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    # ── Moonshot AI ────────────────────────────────────────────────────
    Model(
        id="kimi-k2.7-code",
        provider="github_copilot",
        service_name="github_copilot",
        name="Kimi-K2.7-Code",
        description="Moonshot AI coding-focused model.",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    # ── OpenAI (Chat Completions) ──────────────────────────────────────
    Model(
        id="gpt-4o",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 4o",
        description="",
        capabilities=["tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5-mini",
        provider="github_copilot",
        service_name="github_copilot",
        name="GPT 5 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "thinking", "structured_output"],
        default=False,
        max_context_token=264_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    # ── OpenAI (Responses API / Codex) ─────────────────────────────────
    Model(
        id="gpt-5.3-codex",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.3 Codex",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4-mini",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4 mini",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.4-nano",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.4 nano",
        description="Copilot Pro+ only — available in Codex VS Code extension, not in Copilot Chat.",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=False,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.5",
        provider="github_copilot",
        service_name="copilot_response",
        name="GPT 5.5",
        description="",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default_reasoning="high",
        default=False,
        max_context_token=400_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.6-sol",
        provider="copilot_response",
        name="GPT-5.6 Sol",
        description="Frontier model for complex professional work",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=272_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.6-terra",
        provider="copilot_response",
        name="GPT-5.6 Terra",
        description="GPT-5.6 model that balances intelligence and cost",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=272_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gpt-5.6-luna",
        provider="copilot_response",
        name="GPT-5.6 Luna",
        description="GPT-5.6 model optimized for cost-sensitive workloads",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=272_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    # ── Fine-tuned ─────────────────────────────────────────────────────
    Model(
        id="raptor-mini-tertiary",
        provider="github_copilot",
        service_name="github_copilot",
        name="Raptor mini",
        description="Fine-tuned GPT-5 mini",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        default=True,
        max_context_token=264_000,
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
]
