"""Claude model definitions by Anthropic.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the anthropic service package.
"""

from AgentCrew.modules.llm.types import Model

ANTHROPIC_MODELS = [
    Model(
        id="claude-opus-4-5",
        provider="claude",
        name="Claude 4.5 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=5.0,
        cached_token_price_1m=0.5,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-6",
        provider="claude",
        name="Claude 4.6 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=5.0,
        cached_token_price_1m=0.5,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-7",
        provider="claude",
        name="Claude 4.7 Opus",
        description="Premium model combining maximum intelligence with practical performance",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=1_000_000,
        default=False,
        input_token_price_1m=5.0,
        cached_token_price_1m=0.5,
        output_token_price_1m=25.0,
    ),
    Model(
        id="claude-opus-4-1",
        provider="claude",
        name="Claude 4.1 Opus",
        description="Exceptional model for specialized reasoning tasks",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        default=False,
        input_token_price_1m=15.0,
        cached_token_price_1m=1.5,
        output_token_price_1m=75.0,
    ),
    Model(
        id="claude-sonnet-4-5",
        provider="claude",
        name="Claude 4.5 Sonnet",
        description="Our smartest model for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=3.0,
        cached_token_price_1m=0.3,
        output_token_price_1m=15.0,
    ),
    Model(
        id="claude-sonnet-4-6",
        provider="claude",
        name="Claude 4.6 Sonnet",
        description="Our smartest model for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=3.0,
        cached_token_price_1m=0.3,
        output_token_price_1m=15.0,
    ),
    Model(
        id="claude-sonnet-5",
        provider="claude",
        name="Claude 5 Sonnet",
        description="The most agentic Sonnet model yet with near-Opus performance for complex agents and coding",
        capabilities=["thinking", "tool_use", "vision", "stream"],
        max_context_token=200_000,
        default=False,
        input_token_price_1m=3.0,
        cached_token_price_1m=0.3,
        output_token_price_1m=15.0,
    ),
    Model(
        id="claude-haiku-4-5",
        provider="claude",
        name="Claude 4.5 Haiku",
        description="Our fastest model with near-frontier intelligence",
        max_context_token=200_000,
        capabilities=["tool_use", "vision", "stream", "thinking"],
        input_token_price_1m=0.8,
        cached_token_price_1m=0.1,
        output_token_price_1m=4.0,
    ),
]
