"""CrofAI model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the custom_llm service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

# CrofAI switched to pure pay-as-you-go pricing on May 31, 2026.
# All prices below sourced from https://crof.ai/v1/models API endpoint.

CROFAI_MODELS = [
    Model(
        id="deepseek-v3.2",
        provider="crofai",
        name="DeepSeek V3.2",
        description="DeepSeek V3.2 (Q6_K) on CrofAI, served through the OpenAI-compatible chat completions API.",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default=True,
        max_context_token=163_840,
        input_token_price_1m=0.18,
        output_token_price_1m=0.35,
        cached_token_price_1m=0.04,
    ),
    Model(
        id="deepseek-v4-pro",
        provider="crofai",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro (Q8_0) on CrofAI for agentic and reasoning workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.35,
        output_token_price_1m=0.80,
        cached_token_price_1m=0.003,
    ),
    Model(
        id="deepseek-v4-pro-lightning",
        provider="crofai",
        name="DeepSeek V4 Pro (Lightning)",
        description="DeepSeek V4 Pro Lightning (Q8_0) on CrofAI for faster agentic workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.80,
        output_token_price_1m=1.60,
        cached_token_price_1m=0.02,
    ),
    Model(
        id="deepseek-v4-flash",
        provider="crofai",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash (Q4_0) on CrofAI for lower-latency agentic workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.12,
        output_token_price_1m=0.21,
        cached_token_price_1m=0.003,
    ),
    Model(
        id="glm-5.2",
        provider="crofai",
        name="GLM 5.2",
        description="Z.ai GLM 5.2 (Q8_0) on CrofAI, optimized for long-context agentic workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=400_000,
        input_token_price_1m=0.30,
        output_token_price_1m=1.05,
        cached_token_price_1m=0.05,
    ),
    Model(
        id="glm-5.1",
        provider="crofai",
        name="GLM 5.1",
        description="Z.ai GLM 5.1 (Q8_0) on CrofAI, optimized for long-context agentic workloads.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=202_752,
        input_token_price_1m=0.45,
        output_token_price_1m=2.15,
        cached_token_price_1m=0.08,
    ),
    Model(
        id="glm-5",
        provider="crofai",
        name="GLM 5",
        description="Z.ai GLM 5 (Q4_0) on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        max_context_token=202_752,
        input_token_price_1m=0.48,
        output_token_price_1m=1.90,
        cached_token_price_1m=0.10,
    ),
    Model(
        id="glm-4.7",
        provider="crofai",
        name="GLM 4.7",
        description="Z.AI GLM 4.7 (Q8_0) on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        max_context_token=202_752,
        input_token_price_1m=0.25,
        output_token_price_1m=1.10,
        cached_token_price_1m=0.05,
    ),
    Model(
        id="glm-4.7-flash",
        provider="crofai",
        name="GLM 4.7 Flash",
        description="Z.AI GLM 4.7 Flash (fp8) on CrofAI.",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        max_context_token=131_072,
        input_token_price_1m=0.04,
        output_token_price_1m=0.30,
        cached_token_price_1m=0.008,
    ),
    Model(
        id="greg-1-mini",
        provider="crofai",
        name="Greg 1 Mini",
        description="Crof Greg 1 Mini (Q4_0) — fast lightweight model.",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        max_context_token=229_376,
        input_token_price_1m=0.07,
        output_token_price_1m=0.15,
        cached_token_price_1m=0.01,
    ),
    Model(
        id="greg-2-ultra",
        provider="crofai",
        name="Greg 2 Ultra",
        description="Crof Greg 2 Ultra (int4).",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=229_376,
        input_token_price_1m=3.0,
        output_token_price_1m=10.0,
        cached_token_price_1m=0.50,
    ),
    Model(
        id="greg-2-super",
        provider="crofai",
        name="Greg 2 Super",
        description="Crof Greg 2 Super (int4) — high-capability Greg variant.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=229_376,
        input_token_price_1m=1.50,
        output_token_price_1m=5.00,
        cached_token_price_1m=0.25,
    ),
    Model(
        id="greg-rp",
        provider="crofai",
        name="Greg (Roleplay)",
        description="Crof Greg Roleplay (Q4_0) — roleplay-optimized variant.",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=229_376,
        input_token_price_1m=0.10,
        output_token_price_1m=0.30,
        cached_token_price_1m=0.02,
    ),
    Model(
        id="kimi-k2.6",
        provider="crofai",
        name="Kimi K2.6",
        description="MoonshotAI Kimi K2.6 (int4) on CrofAI with vision and reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.50,
        output_token_price_1m=1.99,
        cached_token_price_1m=0.05,
    ),
    Model(
        id="kimi-k2.7-code",
        provider="crofai",
        name="Kimi K2.7 Code",
        description="MoonshotAI Kimi K2.7 Code on CrofAI with vision and reasoning support — improved long-horizon coding with 30% fewer thinking tokens.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.55,
        output_token_price_1m=2.25,
        cached_token_price_1m=0.05,
    ),
    Model(
        id="kimi-k2.5",
        provider="crofai",
        name="Kimi K2.5",
        description="MoonshotAI Kimi K2.5 (Q4_K_M) on CrofAI with vision and reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.35,
        output_token_price_1m=1.70,
        cached_token_price_1m=0.07,
    ),
    Model(
        id="kimi-k2.5-lightning",
        provider="crofai",
        name="Kimi K2.5 (Lightning)",
        description="MoonshotAI Kimi K2.5 Lightning (530b-int4) on CrofAI with vision and custom reasoning support.",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=131_072,
        input_token_price_1m=1.00,
        output_token_price_1m=3.00,
        cached_token_price_1m=0.20,
    ),
    Model(
        id="gemma-4-31b-it",
        provider="crofai",
        name="Gemma 4 31B",
        description="Google Gemma 4 31B (Q4_0) on CrofAI with reasoning support.",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.10,
        output_token_price_1m=0.30,
        cached_token_price_1m=0.02,
    ),
    Model(
        id="minimax-m2.5",
        provider="crofai",
        name="MiniMax M2.5",
        description="MiniMax M2.5 (awq) on CrofAI for coding and agentic workflows.",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        max_context_token=204_800,
        input_token_price_1m=0.11,
        output_token_price_1m=0.95,
        cached_token_price_1m=0.02,
    ),
    Model(
        id="mimo-v2.5-pro",
        provider="crofai",
        name="MiMo-V2.5-Pro",
        description="Xiaomi MiMo-V2.5-Pro (Q8_0) on CrofAI for agentic workflows.",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="gemma-4-31b-it",
        default_reasoning="medium",
        max_context_token=1_000_000,
        input_token_price_1m=0.40,
        output_token_price_1m=0.80,
        cached_token_price_1m=0.003,
    ),
    Model(
        id="qwen3.5-397b-a17b",
        provider="crofai",
        name="Qwen3.5 397B A17B",
        description="Qwen3.5 397B A17B (Q4_0) on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.35,
        output_token_price_1m=1.75,
        cached_token_price_1m=0.07,
    ),
    Model(
        id="qwen3.5-9b",
        provider="crofai",
        name="Qwen3.5 9B",
        description="Qwen3.5 9B (fp8) on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.04,
        output_token_price_1m=0.15,
        cached_token_price_1m=0.008,
    ),
    Model(
        id="qwen3.6-27b",
        provider="crofai",
        name="Qwen3.6 27B",
        description="Qwen3.6 27B (Q4_0) on CrofAI with custom reasoning support.",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=262_144,
        input_token_price_1m=0.20,
        output_token_price_1m=1.50,
        cached_token_price_1m=0.04,
    ),
]
