"""DeepInfra model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the custom_llm service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

DEEPINFRA_MODELS = [
    Model(
        id="google/gemma-4-31B-it",
        provider="deepinfra",
        name="Gemma 4 31B",
        description="Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.13,
        output_token_price_1m=0.38,
    ),
    Model(
        id="google/gemma-4-26B-A4B-it",
        provider="deepinfra",
        name="Gemma 4 26A4B",
        description="Efficient, MoE variant of Gemma 4",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        input_token_price_1m=0.08,
        output_token_price_1m=0.35,
    ),
    Model(
        id="Qwen/Qwen3.6-35B-A3B",
        provider="deepinfra",
        name="Qwen 3.6",
        description="Qwen3.6-35B-A3B is Alibaba's latest flagship Mixture-of-Experts model",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=1.0,
            top_p=0.95,
            top_k=20,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.2,
        output_token_price_1m=1.00,
    ),
    Model(
        id="Qwen/Qwen3-Coder-480B-A35B-Instruct",
        provider="deepinfra",
        name="Qwen 3 Coder",
        description="Qwen3-Coder-480B-A35B-Instruct is the Qwen3's most agentic code model",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
        ),
        input_token_price_1m=0.4,
        output_token_price_1m=1.6,
    ),
    Model(
        id="Qwen/Qwen3.5-397B-A17B",
        provider="deepinfra",
        name="Qwen 3.5 Big",
        description="Qwen3-Max",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
        ),
        input_token_price_1m=0.54,
        output_token_price_1m=3.40,
    ),
    Model(
        id="Qwen/Qwen3.5-122B-A10B",
        provider="deepinfra",
        name="Qwen 3.5 Medium",
        default_reasoning="minimal",
        description="Qwen3.5-122B-A10B is a large Mixture-of-Experts model from Alibaba's Qwen3.5 series with 122B total parameters and 10B activated per token",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=1.0, top_p=0.95, top_k=20, presence_penalty=1.5
        ),
        max_context_token=256_000,
        input_token_price_1m=0.29,
        output_token_price_1m=2.4,
    ),
    Model(
        id="zai-org/GLM-5",
        provider="deepinfra",
        name="Zai GLM-5",
        description="GLM-5 is an advanced, open-source large language model designed for developers tackling the toughest challenges.",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.8,
        cached_token_price_1m=0.12,
        output_token_price_1m=2.56,
    ),
    Model(
        id="zai-org/GLM-5.2",
        provider="deepinfra",
        name="Zai GLM-5.2",
        description="GLM-5.2 is Z-AI's next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=1.4,
        cached_token_price_1m=0.25,
        output_token_price_1m=4.4,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="deepinfra",
        name="Zai GLM-5.1",
        description="GLM-5.1 is Z-AI's next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor",
        force_sample_params=SampleParam(top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=1.05,
        cached_token_price_1m=0.205,
        output_token_price_1m=3.75,
    ),
    Model(
        id="zai-org/GLM-4.7-Flash",
        provider="deepinfra",
        name="Zai GLM 4.7 Flash",
        description="GLM-4.7-Flash is a 30B-A3B MoE model",
        force_sample_params=SampleParam(temperature=0.7, top_p=1, top_k=40),
        capabilities=["tool_use", "stream"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.06,
        output_token_price_1m=0.4,
    ),
    Model(
        id="Qwen/Qwen3.5-27B",
        provider="deepinfra",
        name="Qwen 3.5 27B",
        description="Qwen3.5 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=1.0,
            top_p=0.95,
            top_k=20,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.26,
        output_token_price_1m=2.6,
    ),
    Model(
        id="Qwen/Qwen3.5-9B",
        provider="deepinfra",
        name="Qwen 3.5 9B",
        description="Qwen3.5 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
            repetition_penalty=1.0,
        ),
        input_token_price_1m=0.1,
        output_token_price_1m=0.15,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="deepinfra",
        name="Kimi K2.5",
        description="Kimi K2.5 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.5,
        cached_token_price_1m=0.07,
        output_token_price_1m=2.0,
    ),
    Model(
        id="nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        provider="deepinfra",
        name="Nemotron 3 Super",
        description="Nemotron 3 Super is a hybrid Mixture-of-Experts (MoE) model engineered for highest compute efficiency and accuracy in multi-agent applications and specialized agentic systems",
        capabilities=["tool_use", "stream", "structured_output", "thinking"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.1,
        output_token_price_1m=0.5,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="deepinfra",
        name="Kimi K2.6",
        description="Kimi K2.6 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.75,
        cached_token_price_1m=0.15,
        output_token_price_1m=3.5,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.5",
        provider="deepinfra",
        name="MiniMax-M2.5",
        description="MiniMax-M2.5 is a Mini model built for Max coding & agentic workflows with just 10 billion activated parameters",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.27,
        cached_token_price_1m=0.03,
        output_token_price_1m=0.95,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Pro",
        provider="deepinfra",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro is an MoE model with 1.6T total parameters (49B active) and a 1M-token context window",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        max_context_token=65_000,
        input_token_price_1m=1.74,
        cached_token_price_1m=0.145,
        output_token_price_1m=3.48,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Flash",
        provider="deepinfra",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash is an efficiency-focused MoE model with 284B total parameters (13B active) and a 1M-token context window",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.14,
        cached_token_price_1m=0.028,
        output_token_price_1m=0.28,
    ),
]
