"""DeepInfra model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the custom_llm service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

DEEPINFRA_MODELS = [
    Model(
        id="google/gemma-4-31B-it",
        provider="deepinfra",
        name="Gemma 4 31B",
        description="Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.13,
        output_token_price_1m=0.38,
    ),
    Model(
        id="google/gemma-4-26B-A4B-it",
        provider="deepinfra",
        name="Gemma 4 26A4B",
        description="Efficient, MoE variant of Gemma 4",
        capabilities=["tool_use", "vision", "stream", "thinking"],
        input_token_price_1m=0.07,
        output_token_price_1m=0.34,
    ),
    Model(
        id="Qwen/Qwen3.6-35B-A3B",
        provider="deepinfra",
        name="Qwen 3.6",
        description="Qwen3.6-35B-A3B is Alibaba's latest flagship Mixture-of-Experts model",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=1.0,
            top_p=0.95,
            top_k=20,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.10,
        output_token_price_1m=0.95,
    ),
    Model(
        id="Qwen/Qwen3-Coder-480B-A35B-Instruct",
        provider="deepinfra",
        name="Qwen 3 Coder",
        description="Qwen3-Coder-480B-A35B-Instruct is the Qwen3's most agentic code model",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
        ),
        input_token_price_1m=0.4,
        output_token_price_1m=1.6,
    ),
    Model(
        id="Qwen/Qwen3.5-397B-A17B",
        provider="deepinfra",
        name="Qwen 3.5 Big",
        description="Qwen3-Max",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
        ),
        input_token_price_1m=0.45,
        output_token_price_1m=3.00,
    ),
    Model(
        id="Qwen/Qwen3.5-122B-A10B",
        provider="deepinfra",
        name="Qwen 3.5 Medium",
        default_reasoning="high",
        description="Qwen3.5-122B-A10B is a large Mixture-of-Experts model from Alibaba's Qwen3.5 series with 122B total parameters and 10B activated per token",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=1.0, top_p=0.95, top_k=20, presence_penalty=1.5
        ),
        max_context_token=256_000,
        input_token_price_1m=0.29,
        output_token_price_1m=2.4,
    ),
    Model(
        id="zai-org/GLM-5",
        provider="deepinfra",
        name="Zai GLM-5",
        description="GLM-5 is an advanced, open-source large language model designed for developers tackling the toughest challenges.",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.8,
        cached_token_price_1m=0.12,
        output_token_price_1m=2.56,
    ),
    Model(
        id="zai-org/GLM-5.2",
        provider="deepinfra",
        name="Zai GLM-5.2",
        description="GLM-5.2 is Z-AI's next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.75,
        cached_token_price_1m=0.14,
        output_token_price_1m=2.40,
    ),
    Model(
        id="zai-org/GLM-5.3-Flash",
        provider="deepinfra",
        name="Zai GLM-5.3 Flash",
        description="GLM-5.3 Flash on DeepInfra — fast, affordable coding model with a 1M context window and vision",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.15,
        cached_token_price_1m=0.03,
        output_token_price_1m=0.50,
    ),
    Model(
        id="zai-org/GLM-5.3",
        provider="deepinfra",
        name="Zai GLM-5.3",
        description="GLM-5.3 on DeepInfra — frontier coding model with emergent cyber capabilities",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=256_000,
        input_token_price_1m=1.20,
        cached_token_price_1m=0.12,
        output_token_price_1m=4.00,
    ),
    Model(
        id="zai-org/GLM-5.1",
        provider="deepinfra",
        name="Zai GLM-5.1",
        description="GLM-5.1 is Z-AI's next-generation flagship model for agentic engineering, with significantly stronger coding capabilities than its predecessor",
        force_sample_params=SampleParam(top_p=0.95, top_k=40),
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=1.05,
        cached_token_price_1m=0.205,
        output_token_price_1m=3.50,
    ),
    Model(
        id="zai-org/GLM-4.7-Flash",
        provider="deepinfra",
        name="Zai GLM 4.7 Flash",
        description="GLM-4.7-Flash is a 30B-A3B MoE model",
        force_sample_params=SampleParam(temperature=0.7, top_p=1, top_k=40),
        capabilities=["tool_use", "stream"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.06,
        output_token_price_1m=0.4,
    ),
    Model(
        id="Qwen/Qwen3.5-27B",
        provider="deepinfra",
        name="Qwen 3.5 27B",
        description="Qwen3.5 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(
            temperature=1.0,
            top_p=0.95,
            top_k=20,
            presence_penalty=1.5,
        ),
        input_token_price_1m=0.26,
        output_token_price_1m=2.6,
    ),
    Model(
        id="Qwen/Qwen3.5-9B",
        provider="deepinfra",
        name="Qwen 3.5 9B",
        description="Qwen3.5 is the latest generation of large language models in Qwen series, offering a comprehensive suite of dense and mixture-of-experts (MoE) models",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=0.95,
            top_k=20,
            repetition_penalty=1.0,
        ),
        input_token_price_1m=0.1,
        output_token_price_1m=0.15,
    ),
    Model(
        id="moonshotai/Kimi-K2.5",
        provider="deepinfra",
        name="Kimi K2.5",
        description="Kimi K2.5 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.5,
        cached_token_price_1m=0.07,
        output_token_price_1m=2.0,
    ),
    Model(
        id="nvidia/NVIDIA-Nemotron-3-Super-120B-A12B",
        provider="deepinfra",
        name="Nemotron 3 Super",
        description="Nemotron 3 Super is a hybrid Mixture-of-Experts (MoE) model engineered for highest compute efficiency and accuracy in multi-agent applications and specialized agentic systems",
        capabilities=["tool_use", "stream", "structured_output", "thinking"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.1,
        output_token_price_1m=0.5,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="deepinfra",
        name="Kimi K2.6",
        description="Kimi K2.6 is an open-source, native multimodal agentic model built through continual pretraining on approximately 15 trillion mixed visual and text tokens atop Kimi-K2-Base",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.75,
        cached_token_price_1m=0.15,
        output_token_price_1m=3.5,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M2.5",
        provider="deepinfra",
        name="MiniMax-M2.5",
        description="MiniMax-M2.5 is a Mini model built for Max coding & agentic workflows with just 10 billion activated parameters",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.27,
        cached_token_price_1m=0.03,
        output_token_price_1m=0.95,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Pro",
        provider="deepinfra",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro is an MoE model with 1.6T total parameters (49B active) and a 1M-token context window",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        max_context_token=65_000,
        input_token_price_1m=1.30,
        cached_token_price_1m=0.10,
        output_token_price_1m=2.60,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Pro-0813",
        provider="deepinfra",
        name="DeepSeek V4 Pro 0813",
        description="DeepSeek-V4-Pro-0813 on DeepInfra — latest DeepSeek V4 Pro release with 1M context and advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        max_context_token=256_000,
        input_token_price_1m=1.30,
        cached_token_price_1m=0.10,
        output_token_price_1m=2.60,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Flash",
        provider="deepinfra",
        name="DeepSeek V4 Flash",
        description="DeepSeek V4 Flash is an efficiency-focused MoE model with 284B total parameters (13B active) and a 1M-token context window",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        input_token_price_1m=0.09,
        cached_token_price_1m=0.018,
        output_token_price_1m=0.18,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Flash-0731",
        provider="deepinfra",
        name="DeepSeek V4 Flash 0731",
        description="DeepSeek-V4-Flash-0731 on DeepInfra — official release of DeepSeek-V4-Flash superseding the preview, with substantially enhanced agentic capabilities",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="google/gemma-4-31B-it",
        max_context_token=400_000,
        input_token_price_1m=0.06,
        cached_token_price_1m=0.015,
        output_token_price_1m=0.18,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
        provider="deepinfra",
        name="DeepSeek V4 Flash Vision Exp",
        description="DeepSeek-V4-Flash-Vision-Exp on DeepInfra — fast hybrid-attention reasoning model with vision",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.44,
        cached_token_price_1m=0.14,
        output_token_price_1m=1.32,
    ),
    Model(
        id="moonshotai/Kimi-K3",
        provider="deepinfra",
        name="Kimi K3",
        description="Kimi K3 on DeepInfra — 2.8T MoE flagship model with 1M context, native vision, and always-on reasoning",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        max_context_token=256_000,
        input_token_price_1m=2.85,
        cached_token_price_1m=0.285,
        output_token_price_1m=14.25,
    ),
    Model(
        id="moonshotai/Kimi-K2.7-Code",
        provider="deepinfra",
        name="Kimi K2.7 Code",
        description="Kimi K2.7 Code on DeepInfra — coding-focused agentic model with improved long-horizon coding and 30% fewer thinking tokens",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        max_context_token=256_000,
        input_token_price_1m=0.68,
        cached_token_price_1m=0.136,
        output_token_price_1m=3.40,
    ),
    Model(
        id="Qwen/Qwen3.8-Max",
        provider="deepinfra",
        name="Qwen 3.8 Max",
        description="Qwen3.8-Max on DeepInfra — agent-first flagship model for coding, reasoning, and long-horizon AI workflows",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=1.65,
        cached_token_price_1m=0.206,
        output_token_price_1m=4.951,
    ),
    Model(
        id="Qwen/Qwen3.8-27B",
        provider="deepinfra",
        name="Qwen 3.8 27B",
        description="Qwen3.8-27B on DeepInfra — compact vision-language model for coding and agentic work",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        max_context_token=262_144,
        input_token_price_1m=0.40,
        cached_token_price_1m=0.04,
        output_token_price_1m=3.00,
    ),
    Model(
        id="nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
        provider="deepinfra",
        name="Nemotron 3 Ultra 550B A55B",
        description="NVIDIA Nemotron 3 Ultra on DeepInfra — open reasoning model for long-horizon autonomous agents",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=262_144,
        input_token_price_1m=0.50,
        cached_token_price_1m=0.10,
        output_token_price_1m=2.20,
    ),
    Model(
        id="nvidia/NVIDIA-Nemotron-3.5-Lightning",
        provider="deepinfra",
        name="Nemotron 3.5 Lightning",
        description="NVIDIA Nemotron 3.5 Lightning on DeepInfra — lightweight reasoning model for high-throughput agentic workloads",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=262_144,
        input_token_price_1m=0.08,
        cached_token_price_1m=0.04,
        output_token_price_1m=0.20,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M3",
        provider="deepinfra",
        name="MiniMax M3",
        description="MiniMax M3 on DeepInfra — coding and agentic model with reasoning support and native multimodality",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=400_000,
        input_token_price_1m=0.28,
        cached_token_price_1m=0.056,
        output_token_price_1m=1.10,
    ),
    Model(
        id="Qwen/Qwen3.8-2.4T-A95B",
        provider="deepinfra",
        name="Qwen 3.8 2.4T A95B",
        description="Qwen3.8-2.4T-A95B is Alibaba's flagship 2.4T-parameter sparse MoE model (~95B active) for coding, long-horizon agentic work, and multimodal reasoning",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=2.0,
        cached_token_price_1m=0.2,
        output_token_price_1m=6.0,
    ),
]
