"""Fireworks AI model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the custom_llm service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

FIREWORKS_MODELS = [
    Model(
        id="accounts/fireworks/models/deepseek-v4-pro",
        provider="fireworks",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro on Fireworks - MoE model with 1.6T total parameters and advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        default=True,
        input_token_price_1m=1.74,
        cached_token_price_1m=0.15,
        output_token_price_1m=3.48,
    ),
    Model(
        id="accounts/fireworks/models/deepseek-v4-pro-0813",
        provider="fireworks",
        name="DeepSeek V4 Pro 0813",
        description="DeepSeek-V4-Pro-0813 on Fireworks - latest DeepSeek V4 Pro release with advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=256_000,
        input_token_price_1m=1.32,
        cached_token_price_1m=0.044,
        output_token_price_1m=3.96,
    ),
    Model(
        id="accounts/fireworks/models/deepseek-v4-flash-0731",
        provider="fireworks",
        name="DeepSeek V4 Flash 0731",
        description="DeepSeek-V4-Flash-0731 on Fireworks — official GA release of V4 Flash with substantially enhanced agentic capabilities",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=400_000,
        input_token_price_1m=0.22,
        cached_token_price_1m=0.007,
        output_token_price_1m=0.66,
    ),
    Model(
        id="accounts/fireworks/models/deepseek-v4-flash-vision-exp",
        provider="fireworks",
        name="DeepSeek V4 Flash Vision Exp",
        description="DeepSeek-V4-Flash-Vision-Exp on Fireworks - fast hybrid-attention reasoning model with vision",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=400_000,
        input_token_price_1m=0.22,
        cached_token_price_1m=0.007,
        output_token_price_1m=0.66,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k3",
        provider="fireworks",
        name="Kimi K3",
        description="Kimi K3 on Fireworks - 2.8T MoE flagship model with 1M context, native vision, and always-on reasoning",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        max_context_token=128_000,
        input_token_price_1m=3.00,
        cached_token_price_1m=0.30,
        output_token_price_1m=15.00,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k2p6",
        provider="fireworks",
        name="Kimi K2.6",
        description="Kimi K2.6 on Fireworks - native multimodal agentic model",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.95,
        cached_token_price_1m=0.16,
        output_token_price_1m=4.0,
    ),
    Model(
        id="accounts/fireworks/models/minimax-m2p7",
        provider="fireworks",
        name="MiniMax M2.7",
        description="MiniMax M2.7 on Fireworks - efficient agentic model with tool use and structured output",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.3,
        cached_token_price_1m=0.06,
        output_token_price_1m=1.2,
    ),
    Model(
        id="accounts/fireworks/models/minimax-m3",
        provider="fireworks",
        name="MiniMax M3",
        description="MiniMax M3 on Fireworks - efficient agentic model with tool use and structured output",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.3,
        cached_token_price_1m=0.06,
        output_token_price_1m=1.2,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p3-flash",
        provider="fireworks",
        name="GLM 5.3 Flash",
        description="GLM-5.3 Flash on Fireworks - fast, affordable coding model with a 1M context window",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=400_000,
        input_token_price_1m=0.15,
        cached_token_price_1m=0.03,
        output_token_price_1m=0.50,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p3",
        provider="fireworks",
        name="GLM 5.3",
        description="GLM-5.3 on Fireworks - Z-AI frontier coding model with emergent cyber capabilities",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=256_000,
        input_token_price_1m=1.40,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.40,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p1",
        provider="fireworks",
        name="GLM 5.1",
        description="GLM-5.1 on Fireworks - Z-AI flagship model for agentic engineering",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        input_token_price_1m=1.4,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.4,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p2",
        provider="fireworks",
        name="GLM 5.2",
        description="GLM-5.2 on Fireworks - Z-AI flagship model for agentic engineering",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        input_token_price_1m=1.4,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.4,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k2p7-code",
        provider="fireworks",
        name="Kimi K2.7 Code",
        description="Kimi K2.7 Code on Fireworks - coding-focused agentic model with improved long-horizon coding and 30% fewer thinking tokens vs K2.6",
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        input_token_price_1m=0.95,
        cached_token_price_1m=0.19,
        output_token_price_1m=4.0,
    ),
    Model(
        id="accounts/fireworks/models/qwen3p7-plus",
        provider="fireworks",
        name="Qwen 3.7 Plus",
        description="Qwen 3.7 Plus on Fireworks - high-performance reasoning model for agentic and coding workflows",
        capabilities=["tool_use", "thinking", "structured_output", "stream", "vision"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=1,
            top_k=40,
        ),
        max_context_token=400_000,
        input_token_price_1m=0.40,
        cached_token_price_1m=0.08,
        output_token_price_1m=1.60,
    ),
    Model(
        id="accounts/fireworks/models/qwen3p8-max",
        provider="fireworks",
        name="Qwen 3.8 Max",
        description="Qwen3.8 Max on Fireworks — agent-first flagship model for coding, reasoning, and long-horizon AI workflows",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=2.00,
        cached_token_price_1m=0.25,
        output_token_price_1m=6.00,
    ),
    Model(
        id="accounts/fireworks/models/qwen3p8-2p4t-a95b",
        provider="fireworks",
        name="Qwen 3.8 2.4T A95B",
        description="Qwen3.8-2.4T-A95B on Fireworks — Alibaba's flagship 2.4T sparse MoE model (~95B active) for autonomous, long-horizon agentic work",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=2.00,
        cached_token_price_1m=0.25,
        output_token_price_1m=6.00,
    ),
    Model(
        id="accounts/fireworks/models/nemotron-lightning-3p5-30b-a3b",
        provider="fireworks",
        name="Nemotron 3.5 Lightning 30B A3B",
        description="NVIDIA Nemotron 3.5 Lightning 30B A3B on Fireworks - lightweight reasoning model for high-throughput agentic workloads",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.05,
        cached_token_price_1m=0.01,
        output_token_price_1m=0.20,
    ),
    Model(
        id="accounts/fireworks/models/nemotron-3-ultra-nvfp4",
        provider="fireworks",
        name="Nemotron 3 Ultra",
        description="NVIDIA Nemotron 3 Ultra on Fireworks - open reasoning model for long-horizon autonomous agents",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=0.60,
        cached_token_price_1m=0.12,
        output_token_price_1m=2.40,
    ),
    Model(
        id="accounts/fireworks/models/muse-glimmer-30b",
        provider="fireworks",
        name="Muse Glimmer 30B",
        description="Meta Muse Glimmer 30B on Fireworks — dense multimodal agent model distilled from Muse Spark, with multi-step reasoning, reliable schema-based tool calling, and vision",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=131_072,
        input_token_price_1m=0.35,
        cached_token_price_1m=0.04,
        output_token_price_1m=1.50,
    ),
]
