"""Fireworks AI model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the custom_llm service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

FIREWORKS_MODELS = [
    Model(
        id="accounts/fireworks/models/deepseek-v4-pro",
        provider="fireworks",
        name="DeepSeek V4 Pro",
        description="DeepSeek V4 Pro on Fireworks - MoE model with 1.6T total parameters and advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        default=True,
        input_token_price_1m=1.74,
        cached_token_price_1m=0.15,
        output_token_price_1m=3.48,
    ),
    Model(
        id="accounts/fireworks/models/deepseek-v4-flash-0731",
        provider="fireworks",
        name="DeepSeek V4 Flash 0731",
        description="DeepSeek-V4-Flash-0731 on Fireworks — official GA release of V4 Flash with substantially enhanced agentic capabilities",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        max_context_token=448_576,
        input_token_price_1m=0.14,
        cached_token_price_1m=0.028,
        output_token_price_1m=0.28,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k3",
        provider="fireworks",
        name="Kimi K3",
        description="Kimi K3 on Fireworks - 2.8T MoE flagship model with 1M context, native vision, and always-on reasoning",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        max_context_token=1_000_000,
        input_token_price_1m=3.00,
        cached_token_price_1m=0.30,
        output_token_price_1m=15.00,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k2p6",
        provider="fireworks",
        name="Kimi K2.6",
        description="Kimi K2.6 on Fireworks - native multimodal agentic model",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.95,
        cached_token_price_1m=0.16,
        output_token_price_1m=4.0,
    ),
    Model(
        id="accounts/fireworks/models/minimax-m2p7",
        provider="fireworks",
        name="MiniMax M2.7",
        description="MiniMax M2.7 on Fireworks - efficient agentic model with tool use and structured output",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.3,
        cached_token_price_1m=0.06,
        output_token_price_1m=1.2,
    ),
    Model(
        id="accounts/fireworks/models/minimax-m3",
        provider="fireworks",
        name="MiniMax M3",
        description="MiniMax M3 on Fireworks - efficient agentic model with tool use and structured output",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=0.6),
        input_token_price_1m=0.3,
        cached_token_price_1m=0.06,
        output_token_price_1m=1.2,
    ),
    Model(
        id="accounts/fireworks/models/qwen3p6-plus",
        provider="fireworks",
        name="Qwen 3.6 Plus",
        description="Qwen 3.6 Plus on Fireworks - latest Qwen MoE model with reasoning capabilities",
        capabilities=["tool_use", "thinking", "structured_output", "stream", "vision"],
        force_sample_params=SampleParam(
            temperature=0.6,
            top_p=1,
            top_k=40,
        ),
        input_token_price_1m=0.5,
        cached_token_price_1m=0.1,
        output_token_price_1m=3.0,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p1",
        provider="fireworks",
        name="GLM 5.1",
        description="GLM-5.1 on Fireworks - Z-AI flagship model for agentic engineering",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        input_token_price_1m=1.4,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.4,
    ),
    Model(
        id="accounts/fireworks/models/glm-5p2",
        provider="fireworks",
        name="GLM 5.2",
        description="GLM-5.2 on Fireworks - Z-AI flagship model for agentic engineering",
        capabilities=["tool_use", "stream", "structured_output"],
        vision_model="accounts/fireworks/models/minimax-m3",
        force_sample_params=SampleParam(temperature=0.7, top_p=0.95, top_k=40),
        input_token_price_1m=1.4,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.4,
    ),
    Model(
        id="accounts/fireworks/models/kimi-k2p7-code",
        provider="fireworks",
        name="Kimi K2.7 Code",
        description="Kimi K2.7 Code on Fireworks - coding-focused agentic model with improved long-horizon coding and 30% fewer thinking tokens vs K2.6",
        force_sample_params=SampleParam(
            temperature=1.0,
        ),
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        input_token_price_1m=0.95,
        cached_token_price_1m=0.19,
        output_token_price_1m=4.0,
    ),
]
