"""Together AI model definitions.

This module only imports `Model` — no heavy service dependencies.
Loaded independently of the together service package.
"""

from AgentCrew.modules.llm.types import Model, SampleParam

TOGETHER_MODELS = [
    Model(
        id="deepseek-ai/DeepSeek-V4-Flash-0731",
        provider="together",
        name="DeepSeek V4 Flash 0731",
        description="DeepSeek-V4-Flash-0731 on Together AI — official GA release of DeepSeek V4 Flash with substantially enhanced agentic capabilities",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        default=True,
        max_context_token=400_000,
        input_token_price_1m=0.14,
        cached_token_price_1m=0.03,
        output_token_price_1m=0.28,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Pro",
        provider="together",
        name="DeepSeek V4 Pro",
        description="General-purpose DeepSeek chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output"],
        input_token_price_1m=1.74,
        cached_token_price_1m=0.20,
        output_token_price_1m=3.48,
    ),
    Model(
        id="deepseek-ai/DeepSeek-V4-Pro-0813",
        provider="together",
        name="DeepSeek V4 Pro 0813",
        description="DeepSeek-V4-Pro-0813 on Together AI — latest DeepSeek V4 Pro release with 1M context and advanced reasoning",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=256_000,
        input_token_price_1m=1.32,
        cached_token_price_1m=0.13,
        output_token_price_1m=3.96,
    ),
    Model(
        id="zai-org/GLM-5.2",
        provider="together",
        name="GLM 5.2 FP4",
        description="General-purpose chat model on Together AI from Z.ai",
        capabilities=["tool_use", "stream", "structured_output"],
        max_context_token=256_000,
        input_token_price_1m=1.40,
        cached_token_price_1m=0.26,
        output_token_price_1m=4.40,
    ),
    Model(
        id="Qwen/Qwen3.7-Max",
        provider="together",
        name="Qwen 3.7 Max",
        description="Qwen3.7 Max on Together AI — agent-first flagship model for coding, reasoning, and long-horizon AI workflows",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=256_000,
        input_token_price_1m=1.25,
        output_token_price_1m=3.75,
    ),
    Model(
        id="Qwen/Qwen3.7-Plus",
        provider="together",
        name="Qwen 3.7 Plus",
        description="Qwen3.7 Plus on Together AI — high-performance reasoning model for agentic and coding workflows",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=0.32,
        output_token_price_1m=1.28,
    ),
    Model(
        id="nvidia/nemotron-3-ultra-550b-a55b",
        provider="together",
        name="Nemotron 3 Ultra 550B A55B",
        description="NVIDIA Nemotron 3 Ultra on Together AI — open reasoning model for long-horizon autonomous agents",
        capabilities=["tool_use", "thinking", "stream", "structured_output"],
        max_context_token=256_000,
        input_token_price_1m=0.60,
        cached_token_price_1m=0.20,
        output_token_price_1m=3.60,
    ),
    Model(
        id="Qwen/Qwen3.5-9B",
        provider="together",
        name="Qwen 3.5 9B FP8",
        description="Small and efficient Qwen chat model on Together AI",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.17,
        output_token_price_1m=0.25,
    ),
    Model(
        id="google/gemma-4-31B-it",
        provider="together",
        name="Gemma 4 31B",
        description="Efficient MiniMax chat model on Together AI",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.39,
        output_token_price_1m=0.97,
    ),
    Model(
        id="MiniMaxAI/MiniMax-M3",
        provider="together",
        name="MiniMax M3 FP4",
        description="Efficient MiniMax chat model on Together AI",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.3,
        output_token_price_1m=1.2,
    ),
    Model(
        id="moonshotai/Kimi-K3",
        provider="together",
        name="Kimi K3",
        description="MoonshotAI Kimi K3 on Together AI - 2.8T MoE flagship model with 1M context, native vision, and always-on reasoning",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        force_sample_params=SampleParam(temperature=1.0),
        max_context_token=128_000,
        input_token_price_1m=3.00,
        cached_token_price_1m=0.30,
        output_token_price_1m=15.00,
    ),
    Model(
        id="moonshotai/Kimi-K2.7-Code",
        provider="together",
        name="Kimi K2.7",
        description="General-purpose Moonshot AI chat model on Together AI",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.95,
        output_token_price_1m=4.0,
    ),
    Model(
        id="moonshotai/Kimi-K2.6",
        provider="together",
        name="Kimi K2.6",
        description="General-purpose Moonshot AI chat model on Together AI",
        capabilities=["tool_use", "stream", "structured_output", "vision"],
        input_token_price_1m=1.2,
        output_token_price_1m=4.5,
    ),
    Model(
        id="thinkingmachines/Inkling",
        provider="together",
        name="Inkling",
        description="Open-weight multimodal MoE model from Thinking Machines Lab (975B total, 41B active) for reasoning, coding, and tool use on Together AI",
        max_context_token=256_000,
        capabilities=["tool_use", "stream", "thinking", "vision", "structured_output"],
        input_token_price_1m=1.0,
        cached_token_price_1m=0.17,
        output_token_price_1m=4.05,
    ),
    Model(
        id="Qwen/Qwen3.8-2.4T-A95B",
        provider="together",
        name="Qwen 3.8 2.4T A95B",
        description="Qwen3.8 Max is the flagship of Qwen's 3.8 generation — 2.4T sparse MoE with 95B active, built for coding, long-horizon agentic work, and multimodal reasoning on Together AI",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=256_000,
        input_token_price_1m=2.50,
        cached_token_price_1m=0.50,
        output_token_price_1m=6.25,
    ),
    Model(
        id="meta-models/Muse-Glimmer-30B",
        provider="together",
        name="Muse Glimmer 30B",
        description="Meta Muse Glimmer 30B on Together AI — dense multimodal agent model from Meta Superintelligence Labs, built for always-on agents with tool use, reasoning, and vision",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="high",
        max_context_token=131_072,
        input_token_price_1m=0.35,
        cached_token_price_1m=0.04,
        output_token_price_1m=1.50,
    ),
]
