from AgentCrew.modules.llm.types import Model

GOOGLE_MODELS = [
    Model(
        id="gemma-4-31b-it",
        provider="google",
        name="Gemma 4 Densed",
        description="Gemma 4 models are multimodal, handling text and image input (with audio supported on small models) and generating text output",
        max_context_token=256_000,
        capabilities=["tool_use", "vision", "structured_output", "thinking"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemma-4-26b-a4b-it",
        provider="google",
        name="Gemma 4 MoE",
        description="Gemma 4 models are multimodal, handling text and image input (with audio supported on small models) and generating text output",
        max_context_token=256_000,
        capabilities=["tool_use", "vision", "structured_output"],
        input_token_price_1m=0.0,
        output_token_price_1m=0.0,
    ),
    Model(
        id="gemini-3.5-flash-lite",
        provider="google",
        name="Gemini 3.5 Flash Lite",
        description="Google's fastest GA Flash model at 350 tok/s, designed for high-volume production workloads with strong price-to-performance ratio.",
        max_context_token=1_000_000,
        capabilities=["tool_use", "vision", "structured_output"],
        input_token_price_1m=0.3,
        cached_token_price_1m=0.03,
        output_token_price_1m=2.5,
    ),
    Model(
        id="gemini-3.6-flash",
        provider="google",
        max_context_token=1_000_000,
        name="Gemini 3.6 Flash",
        description="Google's latest Flash workhorse (Jul 2026) with improved token efficiency — 17% fewer output tokens, lower output pricing, and March 2026 knowledge cutoff.",
        capabilities=["tool_use", "vision", "thinking", "structured_output"],
        input_token_price_1m=1.5,
        cached_token_price_1m=0.15,
        output_token_price_1m=7.5,
        default=True,
    ),
    Model(
        id="gemini-pro-latest",
        provider="google",
        name="Gemini Pro Thinking",
        max_context_token=1_000_000,
        description="Gemini 2.5 Pro with thinking",
        capabilities=["tool_use", "thinking", "vision", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
]
