from AgentCrew.modules.llm.types import Model

OPENAI_MODELS = [
    Model(
        id="gpt-5",
        provider="openai",
        service_name="openai_response",
        name="GPT-5",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
        default=True,
    ),
    Model(
        id="gpt-5-codex",
        provider="openai",
        service_name="openai_response",
        name="GPT-5 Codex",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.1",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.2",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.2",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=400_000,
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.4",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.4",
        default_reasoning="high",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=1_050_000,
        input_token_price_1m=2.5,
        output_token_price_1m=15,
    ),
    Model(
        id="gpt-5.5",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.5",
        default_reasoning="high",
        description="GPT-5 is our flagship model for coding, reasoning, and agentic tasks across domains",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        max_context_token=1_050_000,
        input_token_price_1m=2.5,
        output_token_price_1m=15,
    ),
    Model(
        id="gpt-5.1-codex",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10,
    ),
    Model(
        id="gpt-5.1-codex-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex Mini",
        description="GPT-5-Codex is a version of GPT-5 optimized for agentic coding tasks in Codex or similar environments",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=0.25,
        output_token_price_1m=2.0,
    ),
    Model(
        id="gpt-5.1-codex-max",
        provider="openai",
        service_name="openai_response",
        name="GPT-5.1 Codex Max",
        description="GPT\u20105.1-Codex-Max is purpose-built for agentic coding",
        capabilities=["tool_use", "vision", "thinking", "stream", "structured_output"],
        input_token_price_1m=1.25,
        output_token_price_1m=10.0,
    ),
    Model(
        id="gpt-4.1-mini",
        provider="openai",
        service_name="openai_response",
        name="GPT-4.1 Mini",
        description="small, quick GPT model",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=0.15,
        output_token_price_1m=0.6,
    ),
    Model(
        id="gpt-4.1",
        provider="openai",
        service_name="openai_response",
        name="GPT-4.1",
        description="Flagship model for complex tasks. It is well suited for problem solving across domains",
        capabilities=["tool_use", "vision", "stream", "structured_output"],
        input_token_price_1m=2,
        output_token_price_1m=8,
    ),
    Model(
        id="gpt-5.6-sol",
        provider="openai_response",
        name="GPT-5.6 Sol",
        description="Frontier model for complex professional work",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_050_000,
        input_token_price_1m=5.0,
        output_token_price_1m=30.0,
    ),
    Model(
        id="gpt-5.6-terra",
        provider="openai_response",
        name="GPT-5.6 Terra",
        description="GPT-5.6 model that balances intelligence and cost",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_050_000,
        input_token_price_1m=2.5,
        output_token_price_1m=15.0,
    ),
    Model(
        id="gpt-5.6-luna",
        provider="openai_response",
        name="GPT-5.6 Luna",
        description="GPT-5.6 model optimized for cost-sensitive workloads",
        capabilities=["tool_use", "thinking", "vision", "stream", "structured_output"],
        default_reasoning="medium",
        max_context_token=1_050_000,
        input_token_price_1m=1.0,
        output_token_price_1m=6.0,
    ),
]
